# Generated by Django 3.0.6 on 2020-06-21 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200621_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myapp_attendance_stud', to='myapp.Student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='taught_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myapp_attendance_prof', to='myapp.Student'),
        ),
    ]
