# Generated by Django 3.0.6 on 2020-06-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='taught_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myapp_attendance_prof', to='myapp.Professor'),
        ),
    ]
